spring:
  application:
    name: exam-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/examdb   # đổi 5433
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # thêm dòng này để Hibernate khỏi kêu về Dialect khi DB chưa sẵn
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    banner-mode: "off"

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG  # thấy SQL và binding
    org.springframework.web: INFO